### ISSUE TITLE
Typo in Exercise 1

### ISSUE THREAD

**Issue by psmeros** [epfml/ML_course#2]
In Task C, the domain of the assignment vector α is {0,1}, right?
I mean, in order to be aligned with the python code.
Thanks!

**Comment by Atanahel** [comment]
You mean between the mathematical formulation (1-index-based) and the actual implementation (0-index-based)?

It is common that there might be a mismatch between the math formula and the actual code, ideally you'd want your code to be close to your formulas, but I don't believe modifying the math to fit the code is a really good idea.
