### ISSUE TITLE
Project2, text: glove_solution does not copy data

### ISSUE THREAD

**Issue by sergeivolodin** [epfml/ML_course#37]
Currently, [glove_solution.py](https://github.com/epfml/ML_course/blob/a5505c8/projects/project2/project_text_classification/glove_solution.py#L35) computes a wrong value for `ys`, which is demonstrated by the following example code:

```python
# example matrices parameter
xs = np.eye(5)
ys = np.eye(5)

# example indices parameter
ix = 0
jy = 0

# example scale parameter
scale = 1

# code from glove_solution.py
x, y = xs[ix, :], ys[jy, :]

xs[ix, :] += scale * y
ys[jy, :] += scale * x

print(ys)
```

Outputs
```
 [[ 3.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
```

The problem with the `ys` value is that on the update it uses already modified variable `x` (modified by changing `xs`)

Possible solution: add data copying

**Comment by sergeivolodin** [comment]
Issue can be resolved by #38

**Comment by martinjaggi** [comment]
thanks a lot, we're checking this!

**Comment by martinjaggi** [comment]
actually in the lecture we mentioned that for SGD and alternating minimization, both variants are ok: either updating one factor first and immediately using that state for updating the second factor. or plain SGD, where both updates would be base on the same old information, and therefore not directly influencing (the safe variant)

**Comment by sergeivolodin** [comment]
True. But the second option is more clear for understanding. Thank you!
