### ISSUE TITLE
Clean-up in the repository history

### ISSUE THREAD

**Issue by nibheis** [epfml/ML_course#69]
Hi,

Could you please do some clean-up in the repository history before next semester starts?

A fresh clone gives me:
```
--- /home/git/ML_course -------------------------
  758.9 MiB [##########] /.git                                                                                                                                                                            
   33.6 MiB [          ] /exam
    1.5 MiB [          ] /labs
    4.0 KiB [          ]  .gitignore
    4.0 KiB [          ]  README.md
```
You can use git-filter-branch or [bfg](https://rtyley.github.io/bfg-repo-cleaner/) for that purpose.

Our users (on noto.epfl.ch) have 253 copies (and counting) of this repository, using already 230 GB of disk and about 2 TB of s3 backup/archive space.

Thank you!

**Comment by martinjaggi** [comment]
done
