### ISSUE TITLE
Missing a file (Or something may not be clear)

### ISSUE THREAD

**Issue by glederrey** [epfml/ML_course#8]
Hi,

For the exercise 2 in lab03, the file **plots.py** is importing a file called **build_polynomial**. We are missing this file..

From what I've seen, we are using a function called *build_poly* in this file. Is it the *build_poly* function we wrote just before testing the polynomial regression? 

Thanks

**Comment by glederrey** [comment]
There is something else in this **plots.py**..

I reused the *build_poly* function I created. And to build the matrix, I already added the ones on the left column. Therefore, the line 11 in **plots.py**:
` tx = np.c_[np.ones((len(xvals), 1)), build_poly(xvals, degree)] `
does not work. We have to change it to:
`tx = build_poly(xvals, degree)`

Are we supposed to build the matrix with the ones in the first column or not? 

Thanks

**Comment by IamTao** [comment]
Hello, thank you for your feedback. The function in `build_polynomial.py` is indeed what you need to implement in the notebook. Please copy your implementation to the file `build_polynomial.py`.

Regarding the function `build_poly()`, please check the example that was described in page 2 of the exercise sheet (The first paragraph of that page.)

Let me know if it is still unclear. thx.

**Comment by martinjaggi** [comment]
@glederrey  thanks again for the comment. we have better clarified this in the PDF and code now.

**Comment by glederrey** [comment]
You're welcome.. =)
